### PR TITLE
#123-Restructured-the-profile-and-login Closes #123

### LINKED ISSUE #123: Restructure user profile and and login methods to reflect layered structure
The "business part" of those those features are currently all residing in the controller layer.
Certain methods need to be moved to a service layer

### PR DESCRIPTION
**Pull request by BozhidarLeshev**
Also renamed the userController to ResgistrationController

### CODE REVIEW

**Comment by BozhidarLeshev** [comment]
I tested all the requests with postman and they are working.

**Comment by BozhidarLeshev** [comment]
We will need to test everything using the front end at our meeting.

**Review by adnan-saab — APPROVED** [review]
I don't see any conflicts with the previous changes.

**Review by kknicekewl — APPROVED** [review]
All is good.

**Pull request merged**
